Blogging/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

app_name = 'Blogging'
urlpatterns = [
    path('', views.blog_home, name='BlogHome'),
    path('user_index/', views.UserIndexView.as_view(), name='user_index'),
    path('create_user/', views.signup, name='create_user'),
    path('<int:pk>/', views.ProfileView.as_view(), name='profile_detail'),
    path('login/', auth_views.LoginView.as_view(template_name='Blogging/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='Blogging/logout.html'), name='logout'),
    path('<int:pk>/profile_edit', views.EditProfileView, name='profile_edit'),
]

BobbyWebServer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('BlogHome/', include('Blogging.urls')),
    path('', include('HomeManager.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

HomeManager/urls.py
from django.urls import path
from . import views

app_name = 'HomePageManager'
urlpatterns = [
    path('', views.Home.as_view(), name='HomePage'),
]

Blogging/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.db.models.signals import post_save
import os


def upload_location(instance, filename):
    return f'{instance.user}/{filename}'


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_image = models.ImageField(upload_to=upload_location, null=True, blank=True, default="default/default.jpg",)

    def __str__(self):
        return self.user.first_name+"'s profile"


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(create_user_profile, sender=User)


class Blog(models.Model):
    blog_name = models.CharField(max_length=200)
    blog_text = models.TextField(max_length=10000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.blog_name

HomeManager/models.py
from django.db import models

# Create your models here.

Blogging/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile


class SignUpForm(UserCreationForm):
    # first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    # last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    # email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['bio', 'location', 'birth_date', 'profile_image', ]
        exclude = ['user', ]

Blogging/views.py
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib.auth.models import User
# from .models import Profile
from django.db.models import Q
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from Blogging.forms import SignUpForm, ProfileEditForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.template import RequestContext
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import UserProfile


def blog_home(request):
    return render(request, 'Blogging/BlogHome.html')


class ProfileView(DetailView):
    model = User
    template_name = 'Blogging/profile_detail.html'


class UserIndexView(ListView):
    template_name = 'Blogging/user_index.html'
    model = User

    def get_queryset(self):
        """Return all the users that contain the same string entered in the search bar"""
        query = self.request.GET.get('q')
        object_list = User.objects.filter(Q(username__icontains=query))
        return object_list


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('Blogging:BlogHome')
    else:
        form = SignUpForm()
    return render(request, 'Blogging/create_user.html', {'form': form})


@login_required(login_url='Blogging:login')
def EditProfileView(request, pk):
    user = get_object_or_404(User, id=pk)
    user = request.user
    # user = authenticate(username=user.username, password=user.password)

    # if request.method == 'POST':
    #     form = ProfileEditForm(request.POST or None, request.FILES, instance=user.userprofile)
    #     if form.is_valid():
    #         form.save()

    if user is not None:
        form = ProfileEditForm(request.POST or None,  request.FILES or None, instance=user.userprofile,)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Blogging:profile_detail', kwargs={"pk": user.pk}))
        return render(request, 'Blogging/profile_edit.html', {'form': form})
    else:
        HttpResponseRedirect(reverse('Blogging:BlogHome'))

HomeManager/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView


# Create your views here.
class Home(TemplateView):
    template_name = 'HomeManager/HomePage.html'

Blogging/templates/Blogging/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Blog Home{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>Blog Home</h1>
      {% if user.is_authenticated %}
        <a href="{% url 'Blogging:logout' %}">Logout</a>
      {% else %}
          <a href="{% url 'Blogging:login' %}">Login</a> / <a href="{% url 'Blogging:create_user' %}">Sign Up</a>
      {% endif %}
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

templates/Blogging/BlogHome.html
{% extends 'Blogging/base.html' %}

{% block content %}

<div class="content-container" style="background-color: white">
  <h2>Welcome {{ user.username }}!</h2>
    <form action="{% url 'Blogging:user_index' %}" method="get">
    {% csrf_token %}
        <img src="/static/images/built-in/blog-logo.png" alt="home page image" class="center home-page-image">
        <section>
            <h1>Django API for some simple blogging</h1>
            <div class="input-container">
                <div class="input-container2">
                    <button class="search-icon-button" type="submit">
                        <img src="/static/images/built-in/search-icon.png" alt="search icon" class="search-icon-image">
                    </button>
                    <label for="User" style="width: 90%;">
                        <input class="home-page-input" type="text" placeholder="Search..." name="q">
                    </label>
                </div>
            </div>
            <button class="center" type="submit">Search</button>
            <p class="subhead">This web application is my test of the Django framework. Users can create blogs and alter their profile or view others. </p>
        </section>
    </form>
</div>

{% endblock %}

templates/Blogging/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta http-equiv="Cache-Control" content="max-age=0" />
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta charset="UTF-8">
    <title>{% block title %}Blogging.Bobby{% endblock %}</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" type="text/css" href={% static "css/style.css"%}>
</head>
<body>

<div class="container">
    <header>
        <div class="header-container">
        <a class="header-logo" href="{% url 'Blogging:BlogHome' %}">Blogging.BlogHome</a>
            <nav>
                <ul>
                    <li><a href="{% url 'Blogging:BlogHome' %}"> Home </a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'Blogging:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'Blogging:login' %}">Login</a></li>
                        <li><a href="{% url 'Blogging:create_user' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>
</div>


<div>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</div>

<div class="footer-container">
    <footer>
        This is the footer
    </footer>
</div>

</body>

</html>

templates/Blogging/create_user.html
{% extends 'Blogging/base.html' %}

{% block content %}
<div class="container">
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn waves-effect waves-light red lighten-2" type="submit">Sign up</button>
  </form>
</div>
{% endblock %}

templates/Blogging/login.html
{% extends 'Blogging/base.html' %}

{% block content %}
  <h2>Log in Bobby's Blogging Service</h2>
  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button class="btn waves-effect waves-light red lighten-2" type="submit">Log in</button>
    <a href="{% url 'Blogging:create_user' %}">Need an account so you can blog? Sign up</a>
  </form>
{% endblock %}

templates/Blogging/logout.html
{% extends 'Blogging/base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>You are logged out</h1>
</body>
</html>

<form action="{% url 'Blogging:BlogHome' %}">
    <button class="btn waves-effect waves-light red lighten-2" type="submit">Home Page</button>
</form>
{% endblock %}

templates/Blogging/profile_detail.html
{% extends 'Blogging/base.html' %}
{% block content %}


<div class="profile-corner-container">
    <ul>
        <li><img src="{{ user.userprofile.profile_image.url }}", alt="Avatar" class="detail-profile-pic"></li>
        <li><p>{{ user.first_name }} {{ user.last_name }}</p></li>
        {% if user.userprofile.birth_date %}
            <li><p>{{ user.userprofile.birth_date }}</p></li>
        {% endif %}
        {% if user.userprofile.location %}
            <li><p>{{ user.userprofile.location }}</p></li>
        {% endif %}
    </ul>
</div>


<div class="content-container" style="background-color: white; width:800px; margin-top: 2em">

</div>


<li>
{#    <img src="/static/images/user-xxl.jpg" alt="HTML5 Icon" style="width:50px;height:50px;" >#}
    <img src="{{ user.userprofile.profile_image.url }}" alt="HTML5-icon" style="width:150px;height:150px;" >
</li>

<li>
    Username: {{ user.username }}
</li>

<li>
    First Name: {{ user.first_name }}
</li>

<li>
    Last Name: {{ user.last_name }}
</li>
<li>
    Bio: {{ user.userprofile.bio}}
</li>
<li>
    Birth date: {{ user.userprofile.birth_date}}
</li>

<ul>
  {% for blog in user.blog_set.all %}
    <li>
        Title: "{{ blog.blog_name }}", Published: {{ blog.pub_date }}
    </li>
  {% endfor %}
</ul>

<a class="btn waves-effect waves-light red lighten-2" href="{% url 'Blogging:BlogHome' %}">Home Page</a>
<a class="btn waves-effect waves-light red lighten-2" href="{% url 'Blogging:profile_edit' user.id %}">Edit Profile</a>


<form action="{% url 'Blogging:profile_edit' user.id %}">

</form>

{% endblock %}

templates/Blogging/profile_edit.html
{% extends 'Blogging/base.html' %}
{% block content %}
<h1>{{ user.first_name }} Profile EDIT Page:</h1>

  <form method='POST' action="" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn waves-effect waves-light red lighten-2" type="submit">Save Changes</button>
  </form>
{% endblock %}

templates/Blogging/user_index.html
{% extends 'Blogging/base.html' %}
{% block content %}

<div class="content-container" style="margin: 1em 16%; padding: 1em 0; background-color: whitesmoke">
    <h1>User List:</h1>
</div>

{% if object_list %}
    <ul>
        {% for user in object_list %}
            <li>
                <div class="profile-container">
                    <a href="{% url 'Blogging:profile_detail' user.id %}">
                        {% if user.userprofile.profile_image %}
                            <img src="{{ user.userprofile.profile_image.url }}" alt="profile picture" class="profile-image" style="width:50px;height:50px;" >
                        {% else %}
                            <img src="/media/default/default.jpg" alt="default image">
                        {% endif %}
                    </a>
                    <a href="{% url 'Blogging:profile_detail' user.id %}" style="text-decoration: none" class="name"> {{ user.first_name }} {{ user.last_name }}</a>
                    <p class="user-bio">{{ user.userprofile.bio }}</p>
                </div>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No users were found.</p>
{% endif %}

    <form action="{% url 'Blogging:BlogHome' %}">
        <button class="btn waves-effect waves-light red lighten-2" type="submit">Home Page</button>
    </form>


{% endblock %}

templates/HomeManager/HomePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bobby's Web Server</title>
</head>
<body>
<h1>Bobby's Web Page</h1>
</body>
</html>

<form action="{% url 'Blogging:BlogHome' %}">
    <button type="submit">Blog</button>
</form>

templates/HomeManager/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>